version: '3.3'

services:

    #AAI Resources
    aai-resources:
        build:
           context: .
           dockerfile: aai_resources_init
        container_name: aai-resources
        #depends_on: 
        #    - jce-cassandra
        ports:
            - "8447:8447"
        networks:
            - storage_network    

    #Cassandra
    cassandra:
        image: cassandra:3.11
        container_name: jce-cassandra
        environment:
            - "HEAP_NEWSIZE=1M"
            - "MAX_HEAP_SIZE=1024M"
            - "CASSANDRA_START_RPC=true"
        ports:
            - "9042:9042"
            - "9160:9160"
        networks:
            - storage_network

networks:
    storage_network:
        driver: bridge


