version: '3.3'

services:
    aai-schema-service:
        image: onap/aai-schema-service:1.7.13
        container_name: aai-schema-service
        ports:
            - "8452:8452"
        volumes: 
            - ~/AAI/schema/aai_oxm_v19.xml:/opt/app/aai-schema-service/resources/schema/onap/oxm/v19/aai_oxm_v19.xml
            - ~/AAI/dbedgerule/DbEdgeRules_v19.json:/opt/app/aai-schema-service/resources/schema/onap/dbedgerules/v19/DbEdgeRules_v19.json
        networks:
            - storage_network   
    #Cassandra
    cassandra:
        image: cassandra:3.11
        container_name: jce-cassandra
        environment:
            - "HEAP_NEWSIZE=1M"
            - "MAX_HEAP_SIZE=1024M"
            - "CASSANDRA_START_RPC=true"
        ports:
            - "9042:9042"
            - "9160:9160"
        networks:
            - storage_network

            
    #AAI Resources
    aai-resources:
        image: onap/aai-resources:1.7.2
        container_name: aai-resources
        depends_on: 
            - cassandra
            - aai-schema-service
        ports:
            - "8447:8447"
        volumes: 
            #- ~/AAI/schema/aai_oxm_v19.xml:/opt/app/aai-resources/resources/schema/onap/oxm/v19/aai_oxm_v19.xml
            #- ~/AAI/dbedgerule/DbEdgeRules_v19.json:/opt/app/aai-resources/resources/schema/onap/dbedgerules/v19/DbEdgeRules_v19.json
            - ~/AAI/appprops/janusgraph-realtime.properties:/opt/app/aai-resources/resources/etc/appprops/janusgraph-realtime.properties
            - ~/AAI/appprops/janusgraph-cached.properties:/opt/app/aai-resources/resources/etc/appprops/janusgraph-cached.properties
            - ~/AAI/application.properties:/opt/app/aai-resources/resources/application.properties
        networks:
            - storage_network 

networks:
    storage_network:
        driver: bridge
