version: '3.3'

services:

    #AAI Resources
    aai-resources:
        image: onap/aai-resources:1.7.2
        container_name: aai-resources
        #depends_on: 
        #    - jce-cassandra
        ports:
            - "8447:8447"
        volumes: 
            - ~/AAI/schema:/opt/app/aai-resources/resources/schema/onap/oxm/v20/
            - ~/AAI/dbedgerule:/opt/app/aai-resources/resources/schema/onap/dbedgerules/v20/
            - ~/AAI/appprops/janusgraph-cached.properties:/opt/app/aai-resources/resources/etc/appprops/janusgraph-cached.properties
            - ~/AAI/appprops/janusgraph-realtime.properties:/opt/app/aai-resources/resources/etc/appprops/janusgraph-realtime.properties
        networks:
            - storage_network    

    #Cassandra
    cassandra:
        image: cassandra:3.11
        container_name: jce-cassandra
        environment:
            - "HEAP_NEWSIZE=1M"
            - "MAX_HEAP_SIZE=1024M"
            - "CASSANDRA_START_RPC=true"
        ports:
            - "9042:9042"
            - "9160:9160"
        networks:
            - storage_network

networks:
    storage_network:
        driver: bridge


